services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    networks:
      - debezium
      - food-tech-test_food-tech
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.2
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - debezium
      - food-tech-test_food-tech
    depends_on:
      - zookeeper

  connect:
    image: quay.io/debezium/connect:1.9
    build:
      context: debezium-jdbc-es
      args:
        DEBEZIUM_VERSION: 1.9
    ports:
     - 8083:8083
     - 5005:5005
    links:
     - kafka
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_source_connect_statuses
    networks:
      - debezium
      - food-tech-test_food-tech
    volumes:
      - "kafka_connect:/bitnami"

  debezium-ui:
    container_name: debezium-ui
    image: quay.io/debezium/debezium-ui:1.9
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CONNECT_URIS=http://connect:8083
    depends_on:
      - connect
    networks:
      - debezium
      - food-tech-test_food-tech

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data:z
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      # Bootstrap password.
      # Used to initialize the keystore during the initial startup of
      # Elasticsearch. Ignored on subsequent runs.
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
      xpack.security.enabled: false
    networks:
      - debezium
      - food-tech-test_food-tech

networks:
  debezium:
  food-tech-test_food-tech:
    external: true

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  kafka_connect:
    driver: local
  elasticsearch:
    driver: local
